export const PRESET_STYLES = {
    classic: {
        bg: 'bg-gradient-to-br from-amber-50 to-orange-50',
        card: 'bg-white border border-amber-100 shadow-md',
        title: 'text-gray-900',
        price: 'text-amber-700 bg-amber-50',
        category: 'text-amber-600 bg-amber-50 border-amber-200',
        header: 'bg-white/80 backdrop-blur-md border-b border-amber-100',
        text: 'text-gray-700',
        desc: 'text-gray-500',
        dark: false,
    },
    minimal: {
        bg: 'bg-white',
        card: 'bg-gray-50 border border-gray-100',
        title: 'text-gray-900',
        price: 'text-gray-700 bg-gray-100',
        category: 'text-gray-500 bg-gray-100 border-gray-200',
        header: 'bg-white border-b border-gray-100',
        text: 'text-gray-700',
        desc: 'text-gray-400',
        dark: false,
    },
    menuboard: {
        bg: 'bg-[#1c1c1c]',
        card: 'bg-transparent border-b border-white/10',
        title: 'text-white',
        price: 'text-white',
        category: 'text-gray-300 bg-white/5 border-white/10',
        header: 'bg-[#111] border-b border-white/15',
        text: 'text-white/90',
        desc: 'text-white/50',
        dark: true,
        categoryHeader: 'text-gray-300 border-b border-white/15',
        dots: 'border-white/15',
    },
    'menuboard-light': {
        bg: 'bg-amber-50',
        card: 'bg-transparent border-b border-amber-200/50',
        title: 'text-gray-900',
        price: 'text-gray-900',
        category: 'text-amber-700 bg-amber-100 border-amber-200',
        header: 'bg-white border-b border-amber-200',
        text: 'text-gray-800',
        desc: 'text-gray-400',
        dark: false,
        categoryHeader: 'text-amber-800 border-b border-amber-200',
        dots: 'border-gray-300',
    },
    modern: {
        bg: 'bg-gradient-to-br from-blue-600 via-purple-600 to-indigo-700',
        card: 'bg-white/10 backdrop-blur-lg border border-white/20 shadow-xl',
        title: 'text-white',
        price: 'text-yellow-300 bg-white/10',
        category: 'text-blue-200 bg-white/10 border-white/20',
        header: 'bg-white/10 backdrop-blur-xl border-b border-white/10',
        text: 'text-white/90',
        desc: 'text-white/60',
        dark: true,
    },
    dark: {
        bg: 'bg-[#1a1a2e]',
        card: 'bg-[#16213e] border border-[#0f3460]/50 shadow-lg',
        title: 'text-white',
        price: 'text-emerald-400 bg-emerald-400/10',
        category: 'text-blue-300 bg-blue-400/10 border-blue-400/20',
        header: 'bg-[#0f3460]/80 backdrop-blur-xl border-b border-[#0f3460]',
        text: 'text-gray-200',
        desc: 'text-gray-400',
        dark: true,
    },
    workers: {
        bg: 'bg-gradient-to-br from-orange-600 to-amber-700',
        card: 'bg-white/15 backdrop-blur-sm border border-white/20 shadow-lg',
        title: 'text-white',
        price: 'text-yellow-200 bg-black/20',
        category: 'text-orange-200 bg-black/15 border-orange-300/20',
        header: 'bg-black/20 backdrop-blur-xl border-b border-white/10',
        text: 'text-white/90',
        desc: 'text-white/60',
        dark: true,
    },
    grill: {
        bg: 'bg-gradient-to-br from-gray-900 via-red-950 to-gray-900',
        card: 'bg-red-950/40 border border-red-800/30 shadow-lg',
        title: 'text-red-100',
        price: 'text-orange-400 bg-orange-400/10',
        category: 'text-red-300 bg-red-400/10 border-red-400/20',
        header: 'bg-black/40 backdrop-blur-xl border-b border-red-800/30',
        text: 'text-red-100/90',
        desc: 'text-red-200/50',
        dark: true,
    },
    family: {
        bg: 'bg-gradient-to-br from-pink-50 via-yellow-50 to-blue-50',
        card: 'bg-white border-2 border-pink-100 shadow-md',
        title: 'text-gray-800',
        price: 'text-pink-600 bg-pink-50',
        category: 'text-purple-600 bg-purple-50 border-purple-200',
        header: 'bg-white/80 backdrop-blur-md border-b-2 border-pink-100',
        text: 'text-gray-700',
        desc: 'text-gray-400',
        dark: false,
    },
    pizzeria: {
        bg: 'bg-gradient-to-br from-green-800 via-green-700 to-red-800',
        card: 'bg-white/10 backdrop-blur-sm border border-white/15 shadow-lg',
        title: 'text-white',
        price: 'text-green-200 bg-black/20',
        category: 'text-green-200 bg-green-400/10 border-green-400/20',
        header: 'bg-black/30 backdrop-blur-xl border-b border-white/10',
        text: 'text-white/90',
        desc: 'text-white/60',
        dark: true,
    },
    homecooking: {
        bg: 'bg-gradient-to-br from-amber-100 via-orange-50 to-yellow-100',
        card: 'bg-white border border-amber-200 shadow-md',
        title: 'text-amber-900',
        price: 'text-amber-800 bg-amber-100',
        category: 'text-amber-700 bg-amber-100 border-amber-300',
        header: 'bg-amber-50/80 backdrop-blur-md border-b border-amber-200',
        text: 'text-amber-800',
        desc: 'text-amber-600/60',
        dark: false,
    },
};

export const BADGE_MAP = {
    spicy: '🌶',
    recommended: '⭐',
    new: '🆕',
    value: '💰',
};

export const DESIGN_PRESETS = [
    { id: 'classic', label: 'קלאסי', desc: 'רקע בהיר, כרטיסים פשוטים', tier: 'all', color: 'bg-amber-100 text-amber-700' },
    { id: 'minimal', label: 'מינימלי', desc: 'לבן, רשימה טקסטואלית', tier: 'all', color: 'bg-gray-200 text-gray-600' },
    { id: 'menuboard', label: 'לוח מחירים', desc: 'טקסט בלבד, 21:9 אופטימלי', tier: 'all', color: 'bg-yellow-100 text-yellow-800' },
    { id: 'modern', label: 'מודרני', desc: 'גרדיאנט, כרטיסים מעוגלים', tier: 'pro', color: 'bg-gradient-to-br from-blue-400 to-purple-500 text-white' },
    { id: 'dark', label: 'כהה', desc: 'רקע כהה, קונטרסט גבוה', tier: 'pro', color: 'bg-gray-800 text-white' },
    { id: 'workers', label: 'פועלים', desc: 'בולט, מנות גדולות, גברי', tier: 'pro', color: 'bg-orange-600 text-white' },
    { id: 'grill', label: 'גריל', desc: 'אש, בשרים, עשן', tier: 'pro', color: 'bg-red-700 text-white' },
    { id: 'family', label: 'משפחתי', desc: 'חם, צבעוני, ידידותי', tier: 'pro', color: 'bg-pink-100 text-pink-700' },
    { id: 'pizzeria', label: 'פיצריה', desc: 'איטלקי, אדום-ירוק', tier: 'pro', color: 'bg-green-600 text-white' },
    { id: 'homecooking', label: 'אוכל ביתי', desc: 'כפרי, חם, נוסטלגי', tier: 'pro', color: 'bg-amber-700 text-white' },
];

export const BADGE_OPTIONS = [
    { id: 'spicy', label: '🌶 חריף', emoji: '🌶' },
    { id: 'recommended', label: '⭐ מומלץ', emoji: '⭐' },
    { id: 'new', label: '🆕 חדש', emoji: '🆕' },
    { id: 'value', label: '💰 משתלם', emoji: '💰' },
];

export const PROMO_ICONS = ['🔥', '⭐', '🎉', '💥', '🏷️', '❤️', '👑', '🍽️'];
